title: "Can Selçuk Ücel"
theme: jekyll-theme-minimal
#logo: /assets/logo.png
#show_downloads: true
description: >
  Hello, I am Can Selçuk ÜCEL, a 10th grade high school student from Hisar Schools
  located in İstanbul, Türkiye. I created this GitHub page for my education and
  learning on coding, documentation, and website creation. I am taking the course
  AP Computer Science Principles. In this course I am learning to code, document,
  compress data, collaborate in teams, create educational videos, and more. 
  This page will be the place where I will store my learning, code programs,
  document them, create teaching videos, write paragraphs for collaboration,
  program functions, design and debugging, compress images, and write reflections.
